theme: minima
title: RAPID '21
description: Recent Advances in Power electronics and Industrial Drives
github:
  is_project_page: false
baseurl: /rapid-nssce.github.io
url: https://rapid-nssce.github.io/
