theme: jekyll-theme-slate
title: RAPID '21
# logo: /assets/img/logo.png
description: Recent Advances in Power electronics and Industrial Drives
github:
  is_project_page: false
baseurl: /rapid_conference
url: https://mark-iv-ii.github.io/
